How likely is it that you roll doubles when rolling two dice?



In [4]:
import numpy as np
import pandas as pd



In [5]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[1, 6],
       [2, 4],
       [3, 6],
       ...,
       [3, 6],
       [3, 5],
       [6, 5]])

In [9]:
(pd.DataFrame(rolls)
 .apply(lambda x: x[0] == x[1], axis=1)
 .mean())

0.1631

In [11]:
(pd.DataFrame(rolls)
 .apply(lambda x: x[0] == x[1], axis=1)
 .mean())

0.1631

If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [12]:
n_trials = nrows = 10_000
n_coins = ncols = 8

flips = np.random.choice(['heads','tails'], n_trials * n_coins).reshape(nrows, ncols)
flips

array([['tails', 'tails', 'tails', ..., 'heads', 'heads', 'tails'],
       ['tails', 'heads', 'tails', ..., 'heads', 'tails', 'heads'],
       ['tails', 'tails', 'tails', ..., 'heads', 'tails', 'heads'],
       ...,
       ['tails', 'tails', 'heads', ..., 'tails', 'tails', 'tails'],
       ['tails', 'heads', 'tails', ..., 'tails', 'heads', 'heads'],
       ['tails', 'tails', 'heads', ..., 'tails', 'tails', 'heads']],
      dtype='<U5')

In [21]:
flips == 'heads'

array([[False, False, False, ...,  True,  True, False],
       [False,  True, False, ...,  True, False,  True],
       [False, False, False, ...,  True, False,  True],
       ...,
       [False, False,  True, ..., False, False, False],
       [False,  True, False, ..., False,  True,  True],
       [False, False,  True, ..., False, False,  True]])

In [41]:

total = 0
for ele in flips:
    sum = 0
    for i in ele:
        if i == 'heads':
            sum += 1
    if sum == 3:
        total += 1
print(total)
total / len(flips)

2186


0.2186

In [42]:
total = 0
for ele in flips:
    sum = 0
    for i in ele:
        if i == 'heads':
            sum += 1
    if sum > 3:
        total += 1
print(total)
total / len(flips)

6378


0.6378

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [43]:
n_trials = nrows = 10_000
n_billboards = ncols = 2

billboards = np.random.choice(['webdev','webdev', 'webdev', 'ds'], n_trials * n_billboards).reshape(nrows, ncols)
billboards

array([['ds', 'webdev'],
       ['webdev', 'webdev'],
       ['webdev', 'webdev'],
       ...,
       ['webdev', 'webdev'],
       ['webdev', 'webdev'],
       ['webdev', 'webdev']], dtype='<U6')

In [45]:
(pd.DataFrame(billboards)
 .apply(lambda x: x[0] == 'ds' and x[1] == 'ds', axis=1)
 .mean())

0.0659

Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [61]:
mean = 3
standard_deviation = 1.5
numbers = np.random.normal(mean, standard_deviation, size=(10000,5))
# positive_numbers = numbers > 0

In [62]:
# positives = numbers[positive_numbers]

In [69]:
numbers

array([[ 2.27184291, -0.43495758,  1.38669482,  1.7475314 ,  0.76781841],
       [ 1.59527874,  3.19130469,  4.18679702,  4.40638805,  2.31396599],
       [ 4.10727892,  2.38457994,  5.20059919,  2.80121065,  4.66139943],
       ...,
       [ 3.23847541,  0.82413889,  2.84561284,  2.37366943,  2.52436041],
       [ 2.5677678 ,  2.54062221,  1.53726711,  2.36009497,  2.83995885],
       [ 3.72239815,  1.65502264,  4.65594239,  2.81976043,  1.46607207]])

In [71]:
positives = np.where(numbers < 0,0,numbers)
positives

array([[2.27184291, 0.        , 1.38669482, 1.7475314 , 0.76781841],
       [1.59527874, 3.19130469, 4.18679702, 4.40638805, 2.31396599],
       [4.10727892, 2.38457994, 5.20059919, 2.80121065, 4.66139943],
       ...,
       [3.23847541, 0.82413889, 2.84561284, 2.37366943, 2.52436041],
       [2.5677678 , 2.54062221, 1.53726711, 2.36009497, 2.83995885],
       [3.72239815, 1.65502264, 4.65594239, 2.81976043, 1.46607207]])

In [72]:
(positives.sum(axis=1) < 17).mean()

0.7296

Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
If a man and woman are chosen at random, P(woman taller than man)?

In [78]:
mean = 178
standard_deviation = 8
man = np.random.normal(mean, standard_deviation, size=(10000,1))

In [83]:
man

array([[182.34244602],
       [176.02735832],
       [174.66095369],
       ...,
       [187.67022995],
       [173.52937475],
       [171.80569983]])

In [80]:
mean = 170
standard_deviation = 6
woman = np.random.normal(mean, standard_deviation, size=(10000,1))

In [81]:
woman.mean()

170.01051695071638

In [90]:
(man < woman).mean()

0.2114

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?

In [100]:
p_corrupted = .004
n_times = n_cols = 50
n_simulated = nrows = 10**5

In [101]:
data = np.random.random((nrows, n_cols))
data

array([[0.51232626, 0.85750167, 0.70616626, ..., 0.30650192, 0.54873434,
        0.59735783],
       [0.24316835, 0.22155582, 0.01287757, ..., 0.29255841, 0.04521121,
        0.31505407],
       [0.37293862, 0.53576486, 0.75802573, ..., 0.25928209, 0.70703625,
        0.83109398],
       ...,
       [0.52019186, 0.72949599, 0.39065336, ..., 0.32659935, 0.02788166,
        0.39549804],
       [0.69400458, 0.89866464, 0.45260256, ..., 0.61861418, 0.45403808,
        0.70476743],
       [0.46679457, 0.81281401, 0.46383054, ..., 0.60248368, 0.94603624,
        0.5630641 ]])

In [102]:
corrupted = data < p_corrupted
corrupted

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [103]:
(corrupted.sum(axis=1) >= 1).mean()

0.18192

In [104]:
(corrupted.sum(axis=1) == 0).mean()

0.81808

In [116]:
p_corrupted = .004
n_times = n_cols = 150
n_simulated = nrows = 10**5

In [117]:
data = np.random.random((nrows, n_cols))
corrupted = data < p_corrupted

In [118]:
(corrupted.sum(axis=1) >= 1).mean()

0.4538

In [112]:
p_corrupted = .004
n_times = n_cols = 450
n_simulated = nrows = 10**5

In [113]:
data = np.random.random((nrows, n_cols))
corrupted = data < p_corrupted

In [115]:
(corrupted.sum(axis=1) == 0).mean()

0.16367

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

In [119]:
p_truck = .70
n_day = n_cols = 3
n_simulated = nrows = 10**5

In [120]:
data = np.random.random((nrows, n_cols))
result = data < p_truck

In [121]:
(result.sum(axis=1) == 0).mean()

0.02727

In [122]:
p_truck = .70
n_day = n_cols = 7
n_simulated = nrows = 10**5

In [123]:
data = np.random.random((nrows, n_cols))
result = data < p_truck

In [124]:
(result.sum(axis=1) >= 1).mean()

0.99981

If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [127]:
n_trials = nrows = 10_000
n_people = ncols = 23

bday = np.random.choice(range(1,366), n_trials * n_people).reshape(nrows, ncols)
bday

array([[  9, 207, 275, ..., 231, 210, 216],
       [308, 359, 106, ..., 292, 255,  62],
       [189, 128,  32, ..., 100, 263, 138],
       ...,
       [ 42, 252, 358, ..., 332, 145,  79],
       [220, 110, 128, ..., 106,  15, 119],
       [189, 234, 213, ..., 169, 140,  46]])

In [132]:
def prob_checker(x):
    bday_check = set(x)
    if len(x) != len(bday_check):
        return True
        

In [135]:
(pd.DataFrame(bday)
 .apply(lambda x: len(x) != len(set(x)), axis=1)
 .mean())

0.5123

In [136]:
(pd.DataFrame(bday)
 .apply(lambda x: len(x) != len(set(x)), axis=1)
 .mean())

0.5123

In [137]:
n_trials = nrows = 10_000
n_people = ncols = 20

bday = np.random.choice(range(1,366), n_trials * n_people).reshape(nrows, ncols)
bday

array([[306, 350, 105, ..., 125,   1, 200],
       [145, 291, 269, ...,  25, 132,  95],
       [193, 170,  19, ..., 133,  58,  88],
       ...,
       [ 56,  32,  29, ..., 326, 352,   9],
       [229, 250, 287, ...,  31,  77, 268],
       [331, 339, 162, ..., 205,  84, 365]])

In [138]:
(pd.DataFrame(bday)
 .apply(lambda x: len(x) != len(set(x)), axis=1)
 .mean())

0.4069