How likely is it that you roll doubles when rolling two dice?



In [4]:
import numpy as np
import pandas as pd



In [5]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[1, 6],
       [2, 4],
       [3, 6],
       ...,
       [3, 6],
       [3, 5],
       [6, 5]])

In [9]:
(pd.DataFrame(rolls)
 .apply(lambda x: x[0] == x[1], axis=1)
 .mean())

0.1631

In [11]:
(pd.DataFrame(rolls)
 .apply(lambda x: x[0] == x[1], axis=1)
 .mean())

0.1631

If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [12]:
n_trials = nrows = 10_000
n_coins = ncols = 8

flips = np.random.choice(['heads','tails'], n_trials * n_coins).reshape(nrows, ncols)
flips

array([['tails', 'tails', 'tails', ..., 'heads', 'heads', 'tails'],
       ['tails', 'heads', 'tails', ..., 'heads', 'tails', 'heads'],
       ['tails', 'tails', 'tails', ..., 'heads', 'tails', 'heads'],
       ...,
       ['tails', 'tails', 'heads', ..., 'tails', 'tails', 'tails'],
       ['tails', 'heads', 'tails', ..., 'tails', 'heads', 'heads'],
       ['tails', 'tails', 'heads', ..., 'tails', 'tails', 'heads']],
      dtype='<U5')

In [21]:
flips == 'heads'

array([[False, False, False, ...,  True,  True, False],
       [False,  True, False, ...,  True, False,  True],
       [False, False, False, ...,  True, False,  True],
       ...,
       [False, False,  True, ..., False, False, False],
       [False,  True, False, ..., False,  True,  True],
       [False, False,  True, ..., False, False,  True]])

In [41]:

total = 0
for ele in flips:
    sum = 0
    for i in ele:
        if i == 'heads':
            sum += 1
    if sum == 3:
        total += 1
print(total)
total / len(flips)

2186


0.2186

In [42]:
total = 0
for ele in flips:
    sum = 0
    for i in ele:
        if i == 'heads':
            sum += 1
    if sum > 3:
        total += 1
print(total)
total / len(flips)

6378


0.6378

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [43]:
n_trials = nrows = 10_000
n_billboards = ncols = 2

billboards = np.random.choice(['webdev','webdev', 'webdev', 'ds'], n_trials * n_billboards).reshape(nrows, ncols)
billboards

array([['ds', 'webdev'],
       ['webdev', 'webdev'],
       ['webdev', 'webdev'],
       ...,
       ['webdev', 'webdev'],
       ['webdev', 'webdev'],
       ['webdev', 'webdev']], dtype='<U6')

In [45]:
(pd.DataFrame(billboards)
 .apply(lambda x: x[0] == 'ds' and x[1] == 'ds', axis=1)
 .mean())

0.0659

Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [61]:
mean = 3
standard_deviation = 1.5
numbers = np.random.normal(mean, standard_deviation, size=(10000,5))
# positive_numbers = numbers > 0

In [62]:
# positives = numbers[positive_numbers]

In [69]:
numbers

array([[ 2.27184291, -0.43495758,  1.38669482,  1.7475314 ,  0.76781841],
       [ 1.59527874,  3.19130469,  4.18679702,  4.40638805,  2.31396599],
       [ 4.10727892,  2.38457994,  5.20059919,  2.80121065,  4.66139943],
       ...,
       [ 3.23847541,  0.82413889,  2.84561284,  2.37366943,  2.52436041],
       [ 2.5677678 ,  2.54062221,  1.53726711,  2.36009497,  2.83995885],
       [ 3.72239815,  1.65502264,  4.65594239,  2.81976043,  1.46607207]])

In [71]:
positives = np.where(numbers < 0,0,numbers)
positives

array([[2.27184291, 0.        , 1.38669482, 1.7475314 , 0.76781841],
       [1.59527874, 3.19130469, 4.18679702, 4.40638805, 2.31396599],
       [4.10727892, 2.38457994, 5.20059919, 2.80121065, 4.66139943],
       ...,
       [3.23847541, 0.82413889, 2.84561284, 2.37366943, 2.52436041],
       [2.5677678 , 2.54062221, 1.53726711, 2.36009497, 2.83995885],
       [3.72239815, 1.65502264, 4.65594239, 2.81976043, 1.46607207]])

In [72]:
(positives.sum(axis=1) < 17).mean()

0.7296

Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
If a man and woman are chosen at random, P(woman taller than man)?